### ISSUE TITLE
error message while initiate a dataset

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#12]
server received url https://www.dropbox.com/s/0m8smn04oti92gr/sample_dataset_school_survey.csv?dl=1
TypeError: Cannot redefine a property of an object with external array elements
    at Function.defineProperty (native)
    at getSafe (/usr/lib/meteor/lib/node_modules/request/main.js:897:14)
    at Request.toJSON (/usr/lib/meteor/lib/node_modules/request/main.js:909:10)
    at Object.stringify (native)
    at [object Object].send (app/packages/livedata/livedata_server.js:119:29)
    at [object Object].<anonymous> (app/packages/livedata/livedata_server.js:298:12)
    at app/packages/livedata/livedata_server.js:176:43
Exited with code: 1

**Comment by pld** [comment]
https://github.com/modilabs/bamboo-meteor-client/issues/9, catching a type error will solve this
